### ISSUE TITLE
BLSTM Encoder retreival issue

### ISSUE THREAD

**Issue by ritvikshrivastava** [facebookresearch/InferSent#27]
Got this error while trying to use the pretrained model for generating sentence embeddings on a local dataset:

```
/usr/local/lib/python2.7/dist-packages/torch/serialization.py:284: SourceChangeWarning: source code of class 'models.BLSTMEncoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
26126
Traceback (most recent call last):
  File "sentEmbed.py", line 18, in <module>
    embeddings = infersent.encode(sentences, bsize=128, tokenize=False, verbose=True)
  File "/home/ritvik/InferSent-master/encoder/models.py", line 198, in encode
    sentences, bsize, tokenize, verbose)
  File "/home/ritvik/InferSent-master/encoder/models.py",  line 175, in prepare_samples
    s_f = [word for word in sentences[i] if word in self.word_vec]
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 238, in __getattr__
    type(self).__name__, name))
AttributeError: 'BLSTMEncoder' object has no attribute 'word_vec'

```

Used the latest AllNLI pickle. A similar bug was present in the SentEval repository, but the bug fix there doesn't seem to apply here.

**Comment by aconneau** [comment]
It seems like the GloVe vocab hasn't been loaded.
Did you download GloVe vectors and loaded it in the model using:
`
infersent.build_vocab(sentences, tokenize=True)
`
?

**Comment by ritvikshrivastava** [comment]
Yeah. The Glove file I had downloaded was corrupt. After fixing that, I'm getting this error now:

```
/usr/local/lib/python2.7/dist-packages/torch/serialization.py:284: SourceChangeWarning: source code of class 'models.BLSTMEncoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
26126
Found 10694(/11704) words with glove vectors
Vocab size : 10694
Traceback (most recent call last):
  File "sentEmbed.py", line 19, in <module>
    embeddings = infersent.encode(sentences, tokenize=True)
  File "/home/ritvik/InferSent-master/encoder/models.py", line 209, in encode
    embeddings = np.vstack(embeddings)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by aconneau** [comment]
Could you provide a small example of "sentences" for which you have this problem, so I can try and reproduce this issue.
Thanks a lot

**Comment by ritvikshrivastava** [comment]
Sure! 
When I do `print sentences[:5]`, I get: 
`['EJ Manuel the 1st QB to go in this draft', 'But my bro from the 757 EJ Manuel is the 1st QB gone', 'EJ Manuel the 1st QB to go in this draft', 'Can believe EJ Manuel went as the 1st QB in the draft', 'EJ Manuel the 1st QB to go in this draft']`
It's a part of a processed twitter dataset.
Thank you!

**Comment by aconneau** [comment]
Could you
`print(batch.size()) `
before
`embeddings.append(batch)`
?

**Comment by ritvikshrivastava** [comment]
Yeah seems like an issue here.

```
 File "/home/ritvik/InferSent-master/encoder/models.py", line 208, in encode
    print(batch.size())
TypeError: 'int' object is not callable
```


My code is as follows:

```
from random import randint
import numpy as np
import torch
GLOVE_PATH = '../dataset/GloVe/glove.840B.300d.txt'
infersent = torch.load('infersent.allnli.pickle')
infersent.set_glove_path(GLOVE_PATH)

sentences=[]
with open('/home/ritvik/train.data') as f:
	for line in f:
		line=line.strip()
		tabs=line.split('\t')
		sentences.append(tabs[2])
		sentences.append(tabs[3])

print sentences[:5]
infersent.build_vocab(sentences, tokenize=True)
embeddings = infersent.encode(sentences, tokenize=True)
print('nb sentences encoded : {0}'.format(len(embeddings)))
```

**Comment by aconneau** [comment]
Were you able to run the demo.ipynb without error? ( https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb )
