### ISSUE TITLE
    AssertionError: assert param_from.type() == param_to.type() 

### ISSUE THREAD

**Issue by user55449** [facebookresearch/InferSent#4]
My code:

```
infersent = torch.load('encoder/infersent.allnli.pickle', map_location=lambda storage, loc: storage)
infersent.set_glove_path('/home/my_name/Documents/stackgan/InferSent/dataset/GloVe/glove.840B.300d.txt')

test_sentence = 'This foo is bar.'

infersent.build_vocab([test_sentence], tokenize=True)
encoded = infersent.encode([test_sentence], tokenize=True)
```
```
Traceback (most recent call last):
  File "test_model.py", line 17, in <module>
    encoded = infersent.encode([test_sentence], tokenize=True)
  File "/home/my_name/Documents/stackgan/InferSent/models.py", line 196, in encode
    batch = self.forward((batch, lengths[stidx:stidx + bsize]))
  File "/home/my_name/Documents/stackgan/InferSent/models.py", line 58, in forward
    sent_output = self.enc_lstm(sent_packed)[0] #seqlen x batch x 2*nhid
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 255, in forward
    _copyParams(weight, params)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 183, in _copyParams
    assert param_from.type() == param_to.type()
AssertionError
```
This is Ubuntu with Python 3.6.1 and PyTorch 0.1.12_2 on a GPU, but I'm getting the same problem with Python 2.7. The code runs fine if I specify 
```
infersent.use_cuda = False
``` 
(and I make the correction that @wasiahmad suggests in Issue 5.)

**Comment by user55449** [comment]
My code:

```
infersent = torch.load('encoder/infersent.allnli.pickle', map_location=lambda storage, loc: storage)
infersent.set_glove_path('/home/my_name/Documents/stackgan/InferSent/dataset/GloVe/glove.840B.300d.txt')

test_sentence = 'This foo is bar.'

infersent.build_vocab([test_sentence], tokenize=True)
encoded = infersent.encode([test_sentence], tokenize=True)
```
```
Traceback (most recent call last):
  File "test_model.py", line 17, in <module>
    encoded = infersent.encode([test_sentence], tokenize=True)
  File "/home/my_name/Documents/stackgan/InferSent/models.py", line 196, in encode
    batch = self.forward((batch, lengths[stidx:stidx + bsize]))
  File "/home/my_name/Documents/stackgan/InferSent/models.py", line 58, in forward
    sent_output = self.enc_lstm(sent_packed)[0] #seqlen x batch x 2*nhid
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 255, in forward
    _copyParams(weight, params)
  File "/home/my_name/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 183, in _copyParams
    assert param_from.type() == param_to.type()
AssertionError
```
This is Ubuntu with Python 3.6.1 and PyTorch 0.1.12_2 , but I'm getting the same problem with Python 2.7.

**Comment by user55449** [comment]
Immediately before 

```
sent_output = self.enc_lstm(sent_packed)[0] #seqlen x batch x 2*nhid
```,

sent_packed is 

```
PackedSequence(data=Variable containing:
 0.4421 -0.1307  0.1318  ...  -0.6867 -0.5819 -0.6584
-0.2741  0.2298  0.3588  ...  -0.0308  0.0160  0.1528
 0.4496 -0.2301 -0.0696  ...   0.0838  0.4651  0.1517
          ...             ⋱             ...          
 0.9107 -0.0401  0.5505  ...  -0.3733  0.3653  0.0111
 0.0120  0.2075 -0.1258  ...   0.1387 -0.3605 -0.0350
 0.9652 -0.0138  0.2637  ...  -0.4378 -0.3167 -0.0328
[torch.cuda.FloatTensor of size 7x300 (GPU 0)]
, batch_sizes=[1, 1, 1, 1, 1, 1, 1])
```

and sent_packed[0] is
```
<class 'torch.autograd.variable.Variable'>
Variable containing:
 0.4421 -0.1307  0.1318  ...  -0.6867 -0.5819 -0.6584
-0.2741  0.2298  0.3588  ...  -0.0308  0.0160  0.1528
 0.4496 -0.2301 -0.0696  ...   0.0838  0.4651  0.1517
          ...             ⋱             ...          
 0.9107 -0.0401  0.5505  ...  -0.3733  0.3653  0.0111
 0.0120  0.2075 -0.1258  ...   0.1387 -0.3605 -0.0350
 0.9652 -0.0138  0.2637  ...  -0.4378 -0.3167 -0.0328
[torch.cuda.FloatTensor of size 7x300 (GPU 0)]
```

**Comment by aconneau** [comment]
"infersent = torch.load('encoder/infersent.allnli.pickle', map_location=lambda storage, loc: storage)" will load  the model on CPU, which is not recommended because it's much slower than on GPU.

As mentionned here : https://github.com/facebookresearch/InferSent/blob/master/encoder/play.ipynb in the 2nd cell of the "Load model" part, if you're still using cpu, you need to set infersent.use_cuda=False indeed.
