### ISSUE TITLE
Bug in InnerAttentionMILAEncoder

### ISSUE THREAD

**Issue by OanaMariaCamburu** [facebookresearch/InferSent#53]
Hi,

Thanks for the great work! I'm using both InferSent and SentEval in my research and it's amazing how quickly I can test my models on so many tasks. 

I'm getting this error when running with `encoder_type=InnerAttentionMILAEncoder`:
```
Traceback (most recent call last):

  File "train_nli.py", line 296, in <module>

    train_acc = trainepoch(epoch)

  File "train_nli.py", line 184, in trainepoch

    output = nli_net((s1_batch, s1_len), (s2_batch, s2_len))

  File "/users/oanuru/anaconda3/envs/infersent/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__

    result = self.forward(*input, **kwargs)

  File "/data/dgx1/oanuru/InferSent/models.py", line 815, in forward

    u = self.encoder(s1)

  File "/users/oanuru/anaconda3/envs/infersent/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__

    result = self.forward(*input, **kwargs)

  File "/data/dgx1/oanuru/InferSent/models.py", line 622, in forward

    alphas2.data[0, :, 0])), 1))

RuntimeError: dim out of range - got 1 but the tensor is only 1D
```

**Comment by aconneau** [comment]
Hi,

thanks for your feedback on SentEval and InferSent, I appreciate it :).
Did you find a way to solve this issue? This seems to be related to new changes in pytorch.
If not, I'll look into it.
